### ISSUE TITLE
Dont allow a user to schedule two events at one time

### ISSUE THREAD

**Issue by nheyland** [nheyland/MyWeek#15]
Dont allow a user to schedule two events at one time, this will break the weekly calendar, possible to fix, but it would be awesome if you could make sure this doesn't happen

**Comment by jarthurj** [comment]
Got this done As well as some basic validation. It needs to be implemented into the create function in the views file. I know that Erin working on that though.

**Comment by nheyland** [comment]
Nice! Thank you, do you have a PR for it?
